// Generated by CoffeeScript 1.3.3
(function() {
  var config;

  config = {};

  config.plugins = {};

  config.plugins.sources = [];

  config.plugins.decisions = [];

  config.plugins.actions = [];

  config.plugins.decisions.push(require('./plugins/decisions/alwaysTrue'));

  config.plugins.decisions.push(require('./plugins/decisions/alwaysFalse'));

  config.plugins.actions.push(require('./plugins/actions/printToConsole'));

  config.plugins.actions.push(require('./plugins/actions/sendSms'));

  config.plugins.actions.push(require('./plugins/actions/playMp3'));

  module.exports = config;

}).call(this);
