// Generated by CoffeeScript 1.3.3
(function() {
  var app, application_root, express, path,
    _this = this;

  application_root = __dirname;

  express = require("express");

  path = require("path");

  app = express();

  app.configure((function() {
    app.use(express.bodyParser());
    app.use(express.methodOverride());
    app.use(app.router);
    app.use(express["static"](path.join(application_root, "public")));
    return app.use(express.errorHandler({
      dumpExceptions: true,
      showStack: true
    }));
  }));

  app.get('/', function(req, res) {
    return res.send('Hello World');
  });

  app.get('/api/modules', function(req, res) {
    return res.send([
      {
        name: 'test'
      }
    ]);
  });

  app.get('/api/modules/:name', function(req, res) {
    return res.send({
      name: req.params.name
    });
  });

  app.listen(3000);

  console.log('Listening on port 3000');

}).call(this);
