// Generated by CoffeeScript 1.3.3
(function() {
  var ACCOUNT_SID, AUTH_TOKEN, HOSTNAME, TwilioClient, Twiml, app, client, phone, sys;

  ACCOUNT_SID = "AC1ce0d8d7a79de22f4c27bed657e8e810";

  AUTH_TOKEN = "20f65a9da68ec4630c9c43d19baef94e";

  HOSTNAME = "204.14.154.40:6000";

  app = require('./express');

  sys = require('sys');

  TwilioClient = require('twilio').Client;

  Twiml = require('twilio').Twiml;

  client = new TwilioClient(ACCOUNT_SID, AUTH_TOKEN, HOSTNAME, {
    port: 6000
  });

  phone = client.getPhoneNumber('+14155240379');

  phone.setup(function() {
    return phone.on('incomingCall', function(reqParams, res) {
      console.log('incoming');
      res.append(new Twiml.Say('Thanks for calling! I think you are beautiful!'));
      return res.send();
    });
  });

}).call(this);
