// Generated by CoffeeScript 1.3.3
(function() {
  var Twilio, app, client, express;

  express = require('express');

  Twilio = require('twilio');

  client = new Twilio.RestClient('AC1ce0d8d7a79de22f4c27bed657e8e810', '20f65a9da68ec4630c9c43d19baef94e');

  app = express();

  app.use(express.bodyParser());

  app.get('/', function(request, response) {
    return response.send('Hello World');
  });

  app.post("/respondToVoiceCall", function(request, response) {
    var twiml;
    if (Twilio.validateExpressRequest(request, '20f65a9da68ec4630c9c43d19baef94e')) {
      twiml = new Twilio.TwimlResponse();
      twiml.play("http://www.dialabc.com/i/cache/dtmfgen/wavpcm8.300/9.wav", {
        loop: 50
      });
      response.type("text/xml");
      return response.send(twiml.toString());
    } else {
      return response.send("you are not twilio.  Buzz off.");
    }
  });

  app.listen(process.env.PORT || 5000);

}).call(this);
