// Generated by CoffeeScript 1.3.3
(function() {
  var actions, app, checkDecisionPlugins, config, redis, rtg, saveParameters,
    _this = this;

  this.express = require('express');

  this.twilio = require('twilio');

  config = require('./config');

  if (process.env.REDISTOGO_URL) {
    rtg = require("url").parse(process.env.REDISTOGO_URL);
    redis = require("redis").createClient(rtg.port, rtg.hostname);
    redis.auth(rtg.auth.split(":")[1]);
  } else {
    redis = require("redis").createClient();
  }

  redis.on("error", function(err) {
    return console.log("Error " + err);
  });

  redis.on("connect", function() {
    redis.incr('started');
    return redis.get('started', function(err, response) {
      if (!err) {
        return console.log('Started', response, 'times');
      }
    });
  });

  app = this.express();

  app.use(this.express.bodyParser());

  app.get('/', function(request, response) {
    return response.send('Hello World');
  });

  saveParameters = function(callSid, request) {
    var _this = this;
    if (request.query.pluginHash != null) {
      return redis.hset(callSid, request.query.pluginHash, JSON.stringify(request.body), function(err, response) {
        return console.log('set to redis:', callSid, request.query.pluginHash, response);
      });
    }
  };

  ({
    getParameters: function(callSid, pluginHash) {
      console.log('getting stuff', callSid, pluginHash);
      return redis.hget(callSid, pluginHash, function(err, response) {
        console.log('got from redis:', callSid, pluginHash, response);
        return response;
      });
    }
  });

  checkDecisionPlugins = function(callSid, request, response) {
    var decision, decisionPlugin, _i, _len, _ref;
    decisionPlugin = {};
    _ref = config.plugins.decisions;
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      decisionPlugin = _ref[_i];
      console.log(decisionPlugin);
      decision = decisionPlugin.run(callSid, request, response);
      if (decision.outcome = true) {
        break;
      }
    }
    return actions(callSid, decision, request, response);
  };

  actions = function(callSid, decision, request, response) {
    var actionPlugin, _i, _len, _ref, _results;
    response.type("text/xml");
    _ref = config.plugins.actions;
    _results = [];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      actionPlugin = _ref[_i];
      console.log(actionPlugin);
      if (decision.outcome === true && actionPlugin.runOnTrue === true) {
        _results.push(actionPlugin.run(callSid, request, response));
      } else if (decision.outcome === false && actionPlugin.runOnFalse === true) {
        _results.push(actionPlugin.run(callSid, request, response));
      } else {
        _results.push(void 0);
      }
    }
    return _results;
  };

  app.post("/respondToVoiceCall", function(request, response) {
    var callSid;
    callSid = request.body.CallSid;
    saveParameters(callSid, request);
    if (_this.twilio.validateExpressRequest(request, '20f65a9da68ec4630c9c43d19baef94e')) {
      return checkDecisionPlugins(callSid, request, response);
    } else {
      return response.send("you are not twilio. Buzz off.");
    }
  });

  app.listen(process.env.PORT || 5000);

}).call(this);
