// Generated by CoffeeScript 1.3.3
(function() {
  var Plugin, Twilio, playEnterTone,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Twilio = require('twilio');

  Plugin = require('../plugin');

  playEnterTone = (function(_super) {

    __extends(playEnterTone, _super);

    function playEnterTone() {
      return playEnterTone.__super__.constructor.apply(this, arguments);
    }

    playEnterTone.prototype.runOnTrue = true;

    playEnterTone.prototype.run = function(callSid, request, response, decision) {
      var twiml;
      twiml = new Twilio.TwimlResponse();
      twiml.play("http://www.dialabc.com/i/cache/dtmfgen/wavpcm8.300/9.wav", {
        loop: 50
      });
      return response.send(twiml.toString());
    };

    return playEnterTone;

  })(Plugin);

  module.exports = playEnterTone;

}).call(this);
