// Generated by CoffeeScript 1.3.3
(function() {
  var Twilio, playMp3,
    _this = this;

  Twilio = require('twilio');

  playMp3 = {};

  playMp3.runOnTrue = true;

  playMp3.run = function(request, response) {
    var twiml;
    console.log('playing mp3');
    twiml = new Twilio.TwimlResponse();
    twiml.play("http://www.dialabc.com/i/cache/dtmfgen/wavpcm8.300/9.wav", {
      loop: 50
    });
    console.log(twiml.toString());
    return response.write(twiml.toString());
  };

  module.exports = playMp3;

}).call(this);
