// Generated by CoffeeScript 1.3.3
(function() {
  var playMp3;

  playMp3 = {};

  playMp3.run = function(request, response) {
    var twiml;
    twiml = new Twilio.TwimlResponse();
    twiml.play("http://www.dialabc.com/i/cache/dtmfgen/wavpcm8.300/9.wav", {
      loop: 50
    });
    console.log('playing mp3');
    return response.pipe(twiml.toString(), {
      end: false
    });
  };

  module.exports = playMp3;

}).call(this);
