// Generated by CoffeeScript 1.3.3
(function() {
  var Plugin, Twilio, playMp3,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Twilio = require('twilio');

  Plugin = require('../plugin');

  playMp3 = (function(_super) {

    __extends(playMp3, _super);

    function playMp3() {
      return playMp3.__super__.constructor.apply(this, arguments);
    }

    playMp3.prototype.runOnTrue = true;

    playMp3.prototype.run = function(callSid, request, response) {
      var twiml;
      console.log('playing mp3');
      twiml = new Twilio.TwimlResponse();
      twiml.play("http://www.dialabc.com/i/cache/dtmfgen/wavpcm8.300/9.wav", {
        loop: 50
      });
      console.log(twiml.toString());
      return response.write(twiml.toString());
    };

    return playMp3;

  })(Plugin);

  module.exports = playMp3;

}).call(this);
