// Generated by CoffeeScript 1.3.3
(function() {
  var printToConsole;

  printToConsole = {};

  printToConsole.runOnTrue = true;

  printToConsole.run = function(request, twiml) {
    return console.log('running print to console');
  };

  module.exports = printToConsole;

}).call(this);
