// Generated by CoffeeScript 1.3.3
(function() {
  var Plugin, printToConsole,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Plugin = require('../plugin');

  printToConsole = (function(_super) {

    __extends(printToConsole, _super);

    function printToConsole() {
      return printToConsole.__super__.constructor.apply(this, arguments);
    }

    printToConsole.prototype.runOnTrue = true;

    printToConsole.prototype.run = function(callSid, request, response, decision) {
      return console.log('hai! printinz');
    };

    return printToConsole;

  })(Plugin);

  module.exports = printToConsole;

}).call(this);
