// Generated by CoffeeScript 1.3.3
(function() {
  var Twilio, sendSms;

  Twilio = require('twilio');

  sendSms = {};

  sendSms.runOnTrue = true;

  sendSms.runOnFalse = true;

  sendSms.run = function(request, response) {
    var twiml;
    twiml = new Twilio.TwimlResponse();
    twiml.say("Hi, I'm cool!");
    console.log(twiml.toString());
    return response.write(twiml.toString());
  };

  module.exports = sendSms;

}).call(this);
