// Generated by CoffeeScript 1.3.3
(function() {
  var sendSms;

  sendSms = {};

  sendSms.runOnTrue = true;

  sendSms.runOnFalse = true;

  sendSms.run = function(request, twiml) {
    return console.log('running sms');
  };

  module.exports = sendSms;

}).call(this);
