// Generated by CoffeeScript 1.3.3
(function() {
  var Plugin;

  Plugin = (function() {

    function Plugin(path) {
      var crypto;
      crypto = require('crypto');
      this.hash = crypto.createHash('md5').update(path).digest("hex");
    }

    Plugin.prototype.run = function() {};

    Plugin.prototype.getSourcePlugin = function(name) {
      var source, theSource, _i, _len, _ref;
      theSource = false;
      _ref = global.config.plugins.sources;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        source = _ref[_i];
        if (source.__proto__.constructor.name === name) {
          theSource = source;
          break;
        }
      }
      return theSource;
    };

    return Plugin;

  })();

  module.exports = Plugin;

}).call(this);
