// Generated by CoffeeScript 1.3.3
(function() {
  var alwaysFalse;

  alwaysFalse = {};

  alwaysFalse.run = function(request, twiml) {
    var returnObj;
    returnObj = {};
    returnObj.outcome = false;
    return returnObj;
  };

  module.exports = alwaysFalse;

}).call(this);
