// Generated by CoffeeScript 1.3.3
(function() {
  var Plugin, alwaysTrue,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Plugin = require('../plugin');

  alwaysTrue = (function(_super) {

    __extends(alwaysTrue, _super);

    function alwaysTrue() {
      this.run = __bind(this.run, this);
      return alwaysTrue.__super__.constructor.apply(this, arguments);
    }

    alwaysTrue.prototype.runOnTrue = true;

    alwaysTrue.prototype.run = function(callSid, request, response) {
      var getcode,
        _this = this;
      getcode = this.getSourcePlugin('getCode');
      return getcode.retrieveData(callSid, request, response, function(hasData) {
        var returnObj;
        if (hasData != null) {
          returnObj = {};
          returnObj.outcome = true;
          return returnObj;
        } else {

        }
      });
    };

    return alwaysTrue;

  })(Plugin);

  module.exports = alwaysTrue;

}).call(this);
