// Generated by CoffeeScript 1.3.3
(function() {
  var alwaysTrue;

  alwaysTrue = {};

  alwaysTrue.run = function(request, twiml) {
    var returnObj;
    returnObj = {};
    returnObj.outcome = true;
    return returnObj;
  };

  module.exports = alwaysTrue;

}).call(this);
