// Generated by CoffeeScript 1.3.3
(function() {
  var Plugin, askForCode,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Plugin = require('../plugin');

  askForCode = (function(_super) {

    __extends(askForCode, _super);

    function askForCode() {
      this.run = __bind(this.run, this);
      return askForCode.__super__.constructor.apply(this, arguments);
    }

    askForCode.prototype.run = function(callSid, request, response) {
      var digits, getcode;
      getcode = this.getSourcePlugin('getCode');
      digits = getcode.run(callSid, request, response, '1234');
      return digits === '1234';
    };

    return askForCode;

  })(Plugin);

  module.exports = askForCode;

}).call(this);
