// Generated by CoffeeScript 1.3.3
(function() {
  var Plugin, Twilio, getCode,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Twilio = require('twilio');

  Plugin = require('../plugin');

  getCode = (function(_super) {

    __extends(getCode, _super);

    function getCode() {
      return getCode.__super__.constructor.apply(this, arguments);
    }

    getCode.prototype.runOnTrue = true;

    getCode.prototype.run = function(callSid, request, response) {
      var twiml;
      twiml = new Twilio.TwimlResponse();
      twiml.play('Please dish four numbers at me bro').gather("/respondToVoiceCall?pluginHash=" + this.hash);
      return response.send(twiml.toString());
    };

    return getCode;

  })(Plugin);

  module.exports = getCode;

}).call(this);
