// Generated by CoffeeScript 1.3.3
(function() {
  var Twilio, getCode,
    _this = this;

  Twilio = require('twilio');

  getCode = {};

  getCode.runOnTrue = false;

  getCode.run = function(request, response) {
    return console.log('getting code from dude at the door');
  };

  module.exports = getCode;

}).call(this);
